config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tests
  root 'home#index'
  get  'home/about'

end

app/models/test.rb
class Test < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :tests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = current_user.tests.build
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = current_user.tests.build(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:test, :tester)
    end
    def correct_user
    @test = current_user.tests.find_by(id:params[:id])
    redirect_to tests_path, notice: "Not authorized to edit this pin" if @test.nil?
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    <%random_number=rand(3)%>
      <%case random_number%>
      <%when 0%>
      <%=link_to '#P2P',root_path, class: 'navbar-brand', style: "color:white"%>
      <%when 1%>
      <%=link_to '#Savep2p',root_path, class: 'navbar-brand', style: "color:white"%>
      <%when 2%>
      <%=link_to '#JoinTheCause',root_path, class: 'navbar-brand', style: "color:white"%>
      <%end%>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="nav navbar-nav navbar-right navbar-brand">
        <%if user_signed_in?%>
        <%= link_to "Edit User", edit_user_registration_path, class: 'btn btn-default' %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
        <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default'%>
        <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-default'%>
        <% end %>
        <%=link_to 'Our Mission', home_about_path, class:'btn btn-default' %>
        <%=link_to 'Our Voices', tests_path, class:'btn btn-default '%>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>This is going to be our about us page</h1>
<p>It's going to be epic</p>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>This is the main page.</h1>
<p>It's going to be epic...</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name,msg| %>
<%=content_tag(:div,msg,class:"alert alert-info")%>
<% end %>
<%=render 'home/header'%>
<div class="container">
<%= yield %>
</div>
</body>
</html>